"""UI copy, single source. Jinja: {{ S.key }}. Client JS: window.STR.key. v1 = is only."""

import json

STRINGS: dict[str, dict[str, str]] = {
    "is": {
        # ---- site chrome ----
        "brand": "MtG Kubbur",
        "tagline": "Magic: The Gathering Cube Drafts á Íslandi",
        "nav_stigatafla": "Stigatafla",
        "nav_leikmadur": "Leikmaður",
        "nav_einvigi": "Einvígi",
        "nav_kubbar": "Kubbar",
        "nav_dagatal": "Dagatal",
        "nav_skra": "skrá",
        "nav_standings": "Staðan",
        "footer_apps_label": "Tengd forrit",
        "footer_copyright": "© 2026 MtG Kubbur",
        "loading": "Hleð gögnum…",
        "error": "Villa við að hlaða gögnum",
        # ---- Stigatafla (/) ----
        "index_subtitle": "ELO-stigaröðun",
        "updated_prefix": "Uppfært",
        "cube_filter_label": "Kubbaflokkur:",
        "filter_all": "Allt",
        "filter_high": "High",
        "filter_medium": "Medium",
        "filter_low": "Low",
        "filter_other": "Annað",
        "col_player": "Leikmaður",
        "col_wins": "S",
        "col_losses": "T",
        "col_pct": "%",
        "col_elo": "ELO",
        "col_prev": "Fyrra",
        "col_delta": "±",
        "group_elo": "ELO",
        "group_saeti": "Sæti",
        "search_placeholder": "Leita...",
        # ---- Leikmaður (/throun) ----
        "throun_title": "Leikmaður",
        "throun_desc": "Þróun og tölfræði einstakra leikmanna",
        "player_picker_label": "Leikmaður:",
        "player_picker_placeholder": "Veldu leikmann...",
        "throun_empty": "Veldu leikmann til að sjá upplýsingar",
        "stat_elo": "ELO",
        "stat_saeti": "Sæti",
        "stat_winrate": "Sigurhlutfall",
        "stat_games": "Leikir",
        "stat_best": "Sterkustu kubbar",
        "cube_combined_title": "Árangur og styrkur eftir flokkum",
        "col_styrkur": "Styrkur",
        "detail_summary": "Sundurliðun eftir kubbi",
        "col_games_en": "Games",
        "chart_elo_title": "ELO-stig",
        "chart_rank_title": "Sæti",
        "chart_winrate_title": "Sigurhlutfall",
        "chart_strength_title": "Kubbastyrkur yfir tíma",
        "chart_games_title": "Fjöldi leikja",
        "axis_elo": "ELO",
        "axis_winrate": "Sigurhlutfall (%)",
        "axis_strength": "Kubbaáhrif (γ)",
        "axis_games": "Fjöldi leikja",
        "axis_saeti": "Sæti",
        "legend_90": "90% bil",
        "legend_50": "50% bil",
        "legend_median": "Miðgildi",
        # ---- Einvígi (/einvigi) ----
        "einvigi_title": "Einvígi",
        "einvigi_desc": "Beinn samanburður milli tveggja leikmanna",
        "player1_label": "Leikmaður 1:",
        "player2_label": "Leikmaður 2:",
        "einvigi_empty": "Veldu tvo leikmenn til að sjá einvígið",
        "einvigi_same": "Veldu tvo ólíka leikmenn",
        "no_games": "Engir leikir fundust á milli {p1} og {p2}",
        "vs": "vs",
        "wins_label": "sigrar",
        "total_suffix": "leikir samtals",
        "h2h_cube_title": "Eftir kubbi",
        "col_total": "Samtals",
        "chart_elodiff_title": "ELO-munur yfir tíma",
        "axis_elodiff": "ELO munur",
        "legend_framar": "framar",
        # ---- Kubbar (/kubbar) ----
        "kubbar_title": "Kubbar",
        "kubbar_desc": "Tölfræði og saga einstakra kubba",
        "cube_picker_label": "Kubbur:",
        "cube_picker_placeholder": "Veldu kubb...",
        "kubbar_empty": "Veldu kubb til að sjá upplýsingar",
        "stat_events": "Viðburðir",
        "stat_matches": "Matches",
        "stat_players": "Leikmenn",
        "stat_first": "Fyrst spilað",
        "stat_last": "Síðast spilað",
        "trophy_title": "Bikarhafar",
        "col_bikarar": "Bikarar",
        "rankings_title": "Árangur leikmanna",
        "group_matches": "Matches",
        "group_games": "Games",
        "event_picker_label": "Viðburður:",
        "event_title": "Viðburður",
        # ---- Dagatal (/dagatal) ----
        "dagatal_title": "Dagatal",
        "dagatal_desc": "Dagskrá kubbakvölda",
        "no_upcoming": "Engin viðburðir á dagskrá",
        "upcoming_title": "Væntanlegir viðburðir",
        "col_date": "Dagsetning",
        "col_cube": "Kubbur",
        "col_owner": "Eigandi",
        "col_players": "Leikmenn",
        "past_summary": "Liðnir viðburðir ({n})",
        # ---- Rotisserie (/rotisserie, unlisted) ----
        "rotisserie_title": "Rotisserie-draft",
        "rotisserie_desc": "Meta Memories — staðan í drafti",
        "rotisserie_round": "Umferð",
        "rotisserie_of": "af",
        "rotisserie_picks": "Picks",
        "rotisserie_next": "Næstur",
        "rotisserie_done": "Drafti lokið",
        "rotisserie_last_seen": "Síðasta val séð",
        "rotisserie_pools": "Pools",
        "rotisserie_remaining": "Eftir í kubbnum",
        "rotisserie_log": "Pick log",
        "rotisserie_search": "Leita að spili…",
        "rotisserie_type_all": "Allar tegundir",
        "rotisserie_no_cards": "Engin spil valin enn",
        "rotisserie_no_matches": "Ekkert spil passar við síuna",
        "rotisserie_cards_count": "spil",
        "rotisserie_order_label": "Raða eftir",
        "rotisserie_order_colour": "Color",
        "rotisserie_order_curve": "Curve",
        "rotisserie_order_creature": "Creature / non-creature",
        "rotisserie_order_type": "Card type",
        "rotisserie_sort_name": "Nafni",
        "rotisserie_cmc_label": "Mana value",
        "rotisserie_clear": "Hreinsa síur",
        # ---- Rotisserie deckbuilder (/rotisserie/deck, unlisted) ----
        "rotisserie_deck_title": "Deckbuilder",
        "rotisserie_deck_desc": "Meta Memories — smíðaðu deck úr þínu pooli",
        "rotisserie_deck_link": "Deckbuilder →",
        "rotisserie_deck_back": "← Aftur í draftið",
        "rotisserie_deck_player": "Spilari",
        "rotisserie_deck_deck": "Deck",
        "rotisserie_deck_sideboard": "Sideboard",
        "rotisserie_deck_lands": "Lands",
        "rotisserie_deck_creatures": "Creatures",
        "rotisserie_deck_noncreatures": "Non-creatures",
        "rotisserie_deck_available": "Laus spil — speculation",
        "rotisserie_deck_spec_badge": "Spec",
        "rotisserie_deck_lost_badge": "Taken",
        "rotisserie_deck_total": "Samtals",
        "rotisserie_deck_export": "Afrita decklist",
        "rotisserie_deck_exported": "Afritað!",
        "rotisserie_deck_reset": "Núllstilla",
        "rotisserie_deck_reset_confirm": "Hreinsa allar breytingar fyrir þennan spilara?",
        "rotisserie_deck_to_side": "Í sideboard",
        "rotisserie_deck_to_deck": "Í deckið",
        "rotisserie_deck_switch_pile": "Í hina hrúguna",
        "rotisserie_deck_enlarge": "Skoða spil",
        "rotisserie_deck_add_spec": "Bæta við sem speculation",
        "rotisserie_deck_remove_spec": "Fjarlægja speculation",
        "rotisserie_deck_dismiss": "Hunsa",
        "rotisserie_deck_empty": "Tómt",
        "rotisserie_deck_mana_title": "Mana odds",
        "rotisserie_deck_mana_note": (
            "Líkur á að geta borgað lituð tákn á réttum turn (á play, engin "
            "mulligan), gefið að þú hittir land drops. ✓ = nægar sources fyrir "
            "90–95% öryggi (Karsten 2022). Fetch-lönd telja liti sem þau geta sótt."
        ),
        "rotisserie_deck_mana_turn_prefix": "á T",
        "rotisserie_deck_sources": "sources",
        "rotisserie_deck_mana_joint": "litir saman",
        "rotisserie_deck_lands_hint": "(gott: 16–18)",
        "rotisserie_deck_undo": "Afturkalla",
        "rotisserie_deck_share": "Deila deck",
        "rotisserie_deck_shared": "Hlekkur afritaður!",
        "rotisserie_deck_shared_banner": "Deck hjá",
        "rotisserie_deck_shared_exit": "Opna deckbuilderinn minn",
        "rotisserie_deck_shared_invalid": "Deilihlekkurinn er ógildur eða skemmdur — hér er þinn eigin deckbuilder.",
        "rotisserie_deck_move_col": "Færa í MV súlu",
        "rotisserie_deck_hand_title": "Prufuhönd",
        "rotisserie_deck_hand_new": "Ný hönd",
        "rotisserie_deck_hand_mulligan": "Mulligan",
        "rotisserie_deck_hand_draw": "Draga spil",
        "rotisserie_deck_hand_close": "Loka",
        # MtG hugtök halda ensku heitunum — það er orðaforðinn sem er notaður
        # við borðið (standard English MtG vocabulary, per player request).
        "colour_w": "White",
        "colour_u": "Blue",
        "colour_b": "Black",
        "colour_r": "Red",
        "colour_g": "Green",
        "colour_gold": "Multicolor",
        "colour_colourless": "Colorless",
        "colour_land": "Lands",
        "type_creature": "Creatures",
        "type_instant": "Instants",
        "type_sorcery": "Sorceries",
        "type_artifact": "Artifacts",
        "type_enchantment": "Enchantments",
        "type_planeswalker": "Planeswalkers",
        "type_battle": "Battles",
        "type_land": "Lands",
        "type_noncreature": "Non-creature",
        "type_other": "Annað",
    },
}


def strings_json(lang: str = "is") -> str:
    """Serialise the string table for window.STR (Icelandic kept literal)."""
    return json.dumps(STRINGS.get(lang, STRINGS["is"]), ensure_ascii=False)
