"""UI copy, single source. Jinja: {{ S.key }}. Client JS: window.STR.key. v1 = is only."""

import json

STRINGS: dict[str, dict[str, str]] = {
    "is": {
        # ---- site chrome ----
        "brand": "MtG Kubbur",
        "tagline": "Magic: The Gathering Cube Drafts á Íslandi",
        "nav_stigatafla": "Stigatafla",
        "nav_leikmadur": "Leikmaður",
        "nav_einvigi": "Einvígi",
        "nav_kubbar": "Kubbar",
        "nav_dagatal": "Dagatal",
        "nav_skra": "skrá",
        "nav_standings": "Staðan",
        "footer_apps_label": "Tengd forrit",
        "footer_copyright": "© 2026 MtG Kubbur",
        "loading": "Hleð gögnum…",
        "error": "Villa við að hlaða gögnum",
        # ---- Stigatafla (/) ----
        "index_subtitle": "ELO-stigaröðun",
        "updated_prefix": "Uppfært",
        "cube_filter_label": "Kubbaflokkur:",
        "filter_all": "Allt",
        "filter_high": "High",
        "filter_medium": "Medium",
        "filter_low": "Low",
        "filter_other": "Annað",
        "col_player": "Leikmaður",
        "col_wins": "S",
        "col_losses": "T",
        "col_pct": "%",
        "col_elo": "ELO",
        "col_prev": "Fyrra",
        "col_delta": "±",
        "group_elo": "ELO",
        "group_saeti": "Sæti",
        "search_placeholder": "Leita...",
        # ---- Leikmaður (/throun) ----
        "throun_title": "Leikmaður",
        "throun_desc": "Þróun og tölfræði einstakra leikmanna",
        "player_picker_label": "Leikmaður:",
        "player_picker_placeholder": "Veldu leikmann...",
        "throun_empty": "Veldu leikmann til að sjá upplýsingar",
        "stat_elo": "ELO",
        "stat_saeti": "Sæti",
        "stat_winrate": "Sigurhlutfall",
        "stat_games": "Leikir",
        "stat_best": "Sterkustu kubbar",
        "cube_combined_title": "Árangur og styrkur eftir flokkum",
        "col_styrkur": "Styrkur",
        "detail_summary": "Sundurliðun eftir kubbi",
        "col_games_en": "Games",
        "chart_elo_title": "ELO-stig",
        "chart_rank_title": "Sæti",
        "chart_winrate_title": "Sigurhlutfall",
        "chart_strength_title": "Kubbastyrkur yfir tíma",
        "chart_games_title": "Fjöldi leikja",
        "axis_elo": "ELO",
        "axis_winrate": "Sigurhlutfall (%)",
        "axis_strength": "Kubbaáhrif (γ)",
        "axis_games": "Fjöldi leikja",
        "axis_saeti": "Sæti",
        "legend_90": "90% bil",
        "legend_50": "50% bil",
        "legend_median": "Miðgildi",
        # ---- Einvígi (/einvigi) ----
        "einvigi_title": "Einvígi",
        "einvigi_desc": "Beinn samanburður milli tveggja leikmanna",
        "player1_label": "Leikmaður 1:",
        "player2_label": "Leikmaður 2:",
        "einvigi_empty": "Veldu tvo leikmenn til að sjá einvígið",
        "einvigi_same": "Veldu tvo ólíka leikmenn",
        "no_games": "Engir leikir fundust á milli {p1} og {p2}",
        "vs": "vs",
        "wins_label": "sigrar",
        "total_suffix": "leikir samtals",
        "h2h_cube_title": "Eftir kubbi",
        "col_total": "Samtals",
        "chart_elodiff_title": "ELO-munur yfir tíma",
        "axis_elodiff": "ELO munur",
        "legend_framar": "framar",
        # ---- Kubbar (/kubbar) ----
        "kubbar_title": "Kubbar",
        "kubbar_desc": "Tölfræði og saga einstakra kubba",
        "cube_picker_label": "Kubbur:",
        "cube_picker_placeholder": "Veldu kubb...",
        "kubbar_empty": "Veldu kubb til að sjá upplýsingar",
        "stat_events": "Viðburðir",
        "stat_matches": "Matches",
        "stat_players": "Leikmenn",
        "stat_first": "Fyrst spilað",
        "stat_last": "Síðast spilað",
        "trophy_title": "Bikarhafar",
        "col_bikarar": "Bikarar",
        "rankings_title": "Árangur leikmanna",
        "group_matches": "Matches",
        "group_games": "Games",
        "event_picker_label": "Viðburður:",
        "event_title": "Viðburður",
        # ---- Dagatal (/dagatal) ----
        "dagatal_title": "Dagatal",
        "dagatal_desc": "Dagskrá kubbakvölda",
        "no_upcoming": "Engin viðburðir á dagskrá",
        "upcoming_title": "Væntanlegir viðburðir",
        "col_date": "Dagsetning",
        "col_cube": "Kubbur",
        "col_owner": "Eigandi",
        "col_players": "Leikmenn",
        "past_summary": "Liðnir viðburðir ({n})",
        # ---- Rotisserie (/rotisserie, unlisted) ----
        "rotisserie_title": "Rotisserie-draft",
        "rotisserie_desc": "Meta Memories — staðan í drafti",
        "rotisserie_round": "Umferð",
        "rotisserie_of": "af",
        "rotisserie_picks": "Val",
        "rotisserie_next": "Næstur",
        "rotisserie_done": "Drafti lokið",
        "rotisserie_last_seen": "Síðasta val séð",
        "rotisserie_pools": "Spilastokkar",
        "rotisserie_remaining": "Eftir í kubbnum",
        "rotisserie_log": "Valsaga",
        "rotisserie_search": "Leita að spili…",
        "rotisserie_type_all": "Allar tegundir",
        "rotisserie_no_cards": "Engin spil valin enn",
        "rotisserie_no_matches": "Ekkert spil passar við síuna",
        "rotisserie_cards_count": "spil",
        "rotisserie_expand": "Sýna",
        "rotisserie_collapse": "Fela",
        "colour_w": "Hvítur",
        "colour_u": "Blár",
        "colour_b": "Svartur",
        "colour_r": "Rauður",
        "colour_g": "Grænn",
        "colour_gold": "Fjöllitur",
        "colour_colourless": "Litlaus",
        "colour_land": "Lönd",
        "type_creature": "Skepnur",
        "type_instant": "Skyndi",
        "type_sorcery": "Galdrar",
        "type_artifact": "Gripir",
        "type_enchantment": "Álög",
        "type_planeswalker": "Planeswalker",
        "type_land": "Lönd",
    },
}


def strings_json(lang: str = "is") -> str:
    """Serialise the string table for window.STR (Icelandic kept literal)."""
    return json.dumps(STRINGS.get(lang, STRINGS["is"]), ensure_ascii=False)
